[/Script/EngineSettings.GameMapsSettings]
; Leeres Beispielprojekt — Maps hier eintragen, sobald vorhanden.

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum
